home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('logging-in/', include('login_feature.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
]

trigger2/urls.py
from django.urls import path

from . import views

app_name = 'trigger2'

urlpatterns = [
    path('', views.index, name='index'),
    path('permohonan-sumber-daya', views.permohonan_sumber_daya, name='permohonan_sumber_daya'),
    path('create-permohonan-sumber-daya', views.create_permohonan, name='create_permohonan'),
    path('update-permohonan-sumber-daya', views.update_permohonan, name='update_permohonan'),
    path('delete-permohonan-sumber-daya', views.delete_permohonan, name='delete_permohonan'),
    path('riwayat-permohonan-sumber-daya', views.riwayat_permohonan_sumber_daya, name='riwayat_permohonan_sumber_daya'),
    path('create-riwayat', views.create_riwayat, name='create_riwayat'),
    path('proses-riwayat', views.proses_riwayat, name='proses_riwayat'),
    path('proses-riwayat-final', views.proses_riwayat_final, name='proses_riwayat_final'),
    path('item-sumber-daya', views.item_sumber_daya, name='item_sumber_daya'),
    path('create-item', views.create_item, name='create_item'),
    path('update-item', views.update_item, name='update_item'),
    path('delete-item', views.delete_item, name='delete_item'),
]

trigger4/urls.py
from django.urls import path

from . import views

app_name = 'trigger4'

urlpatterns = [
    path('', views.index, name='index'),
    path('lokasi', views.lokasi, name='lokasi'),
    path('form-lokasi', views.form_lokasi, name='form_lokasi'),
    path('update-lokasi', views.update_lokasi, name='update_lokasi'),
    path('batch-pengiriman', views.batch_pengiriman, name='batch_pengiriman'),
    path('create-batch', views.create_batch, name='create_batch'),
    path('detail-batch', views.detail_batch, name='detail_batch'),
    path('kendaraan', views.kendaraan, name='kendaraan'),
    path('create-kendaraan', views.create_kendaraan, name='create_kendaraan'),
    path('update-kendaraan', views.update_kendaraan, name='update_kendaraan'),
    path('delete-kendaraan', views.delete_kendaraan, name='delete_kendaraan'),
]

trigger2/models.py
from django.db import models

# Create your models here.

trigger2/views.py
from django.shortcuts import render, redirect
from django.db import connection, IntegrityError
from django.db.utils import InternalError
from django.contrib import messages
from datetime import datetime
from datetime import date
import random


def index(request):
    context = {
        "role" : request.session["role"]
    }

    return render(request, 'trigger2/index.html', context)

def item_sumber_daya(request):
    response = {}
    response['items'] = []
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM ITEM_SUMBER_DAYA")
        fetched = cursor.fetchall()
        for i in range(len(fetched)):
            response['items'].append([
                fetched[i][0],
                fetched[i][1],
                fetched[i][2],
                fetched[i][3],
                fetched[i][4],
                fetched[i][5],
            ]) 
    return render(request, 'trigger2/item-sumber-daya.html', response)

def create_item(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                #coded = str(request.POST["kode_item"])[2:5]
                cursor.execute(f"""
                    INSERT INTO ITEM_SUMBER_DAYA (kode, username_supplier, nama, harga_satuan, berat_satuan, kode_tipe_item) VALUES
                    ('{request.POST["kode"]}', '{request.POST["user_supplier"]}', '{request.POST["nama"]}'
                    , {request.POST["harga"]}, {request.POST["berat"]}, '{request.POST["kode_item"]}') """)
                
                # return redirect("")
                messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                return redirect("trigger2:item_sumber_daya")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")

    else:
        response['code'] = []
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM TIPE_ITEM")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['code'].append(fetched[i][0]) 
    return render(request, 'trigger2/create-item.html', response)


def update_item(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""
                    SELECT * FROM ITEM_SUMBER_DAYA WHERE kode='{request.POST["kode"]}'""")
                temp_data = cursor.fetchall()

                if (len(temp_data) > 0):
                    coded = str(request.POST["kode_item"])
                    new_supp = str(temp_data[0][1]) if str(request.POST["user_supplier"]) == "" else str(request.POST["user_supplier"])
                    new_name = str(temp_data[0][2]) if str(request.POST["nama"]) == "" else str(request.POST["nama"])
                    new_harga = str(temp_data[0][3]) if str(request.POST["harga"]) == "" else str(request.POST["harga"])
                    new_berat = str(temp_data[0][4]) if str(request.POST["berat"]) == "" else str(request.POST["berat"])
                    new_coded = str(temp_data[0][5]) if str(request.POST["kode_item"]) == "" else coded


                    cursor.execute(f"""
                        UPDATE ITEM_SUMBER_DAYA SET kode='{request.POST["kode"]}', username_supplier='{new_supp}',nama='{new_name}', 
                        harga_satuan={new_harga}, berat_satuan={new_berat}, kode_tipe_item='{new_coded}'  WHERE kode='{request.POST["kode"]}'""")
                    messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                    return redirect("trigger2:item_sumber_daya")
                else:
                    messages.add_message(request, messages.WARNING, f"“Data tidak ada")
    
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Data salah")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")
    else:
        response['code'] = []
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM TIPE_ITEM")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['code'].append(fetched[i][0]) 
    return render(request, 'trigger2/update-item.html', response)


def delete_item(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""DELETE FROM ITEM_SUMBER_DAYA WHERE kode='{request.POST["kode"]}'""")
                messages.add_message(request, messages.SUCCESS, f"Penghapusan berhasil")
                return redirect("trigger2:item_sumber_daya")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")
    return render(request, 'trigger2/delete-item.html')


def permohonan_sumber_daya(request):
    response = {}
    response['psd'] = []
    with connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT p.no_transaksi_sumber_daya, p.username_petugas_faskes, p.catatan, t.tanggal, t.total_item, t.total_berat
            FROM PERMOHONAN_SUMBER_DAYA_FASKES AS p, TRANSAKSI_SUMBER_DAYA AS t WHERE p.no_transaksi_sumber_daya = t.nomor""")
        fetched = cursor.fetchall()
        for i in range(len(fetched)):
            response['psd'].append([
                fetched[i][0],
                fetched[i][1],
                fetched[i][2],
                fetched[i][3],
                fetched[i][4],
                fetched[i][5],
            ]) 
    return render(request, 'trigger2/permohonan-sumber-daya.html', response)

def create_permohonan(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                coded = str(request.POST["kode_item"])[2:5]
                date_today = date.today()

                cursor.execute(f""" SELECT nomor FROM TRANSAKSI_SUMBER_DAYA""")
                length = len(cursor.fetchall()) + 1
            
                cursor.execute(f"""
                    INSERT INTO TRANSAKSI_SUMBER_DAYA (nomor, tanggal, total_berat, total_item) VALUES
                    ('{length}', '{date_today}', {request.POST["berat"]}, {request.POST["jumlah"]}) """)

                if request.POST["catatan"] == "":
                    cursor.execute(f"""
                        INSERT INTO PERMOHONAN_SUMBER_DAYA_FASKES (no_transaksi_sumber_daya, username_petugas_faskes, catatan) VALUES
                        ('{length}', '{request.POST["petugas"]}', NULL) """)

                else:
                    cursor.execute(f"""
                        INSERT INTO PERMOHONAN_SUMBER_DAYA_FASKES (no_transaksi_sumber_daya, username_petugas_faskes, catatan) VALUES
                        ('{length}', '{request.POST["petugas"]}', {request.POST["catatan"]}) """)
                
                # return redirect("")
                messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                return redirect("trigger2:permohonan_sumber_daya")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")

    else:
        response['code'] = []
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM ITEM_SUMBER_DAYA")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['code'].append([
                    fetched[i][0],
                ]) 
    return render(request, 'trigger2/create-permohonan.html', response)

def delete_permohonan(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""DELETE FROM PERMOHONAN_SUMBER_DAYA_FASKES WHERE no_transaksi_sumber_daya='{request.POST["kode"]}'""")
                cursor.execute(f"""DELETE FROM TRANSAKSI_SUMBER_DAYA WHERE nomor='{request.POST["kode"]}'""")
                messages.add_message(request, messages.SUCCESS, f"Penghapusan berhasil")
                return redirect("trigger2:permohonan_sumber_daya")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")
    return render(request, 'trigger2/delete-permohonan.html')

def update_permohonan(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""
                    SELECT p.no_transaksi_sumber_daya, p.username_petugas_faskes, p.catatan, t.tanggal, t.total_item, t.total_berat
                    FROM PERMOHONAN_SUMBER_DAYA_FASKES AS p, TRANSAKSI_SUMBER_DAYA AS t WHERE p.no_transaksi_sumber_daya = t.nomor 
                    AND p.no_transaksi_sumber_daya = {request.POST["nomor"]}""")
                temp_data = cursor.fetchall()

                if (len(temp_data) > 0):
                    coded = str(request.POST["kode_item"])[2:5]
                    date_today = date.today()
                    new_berat = ""
                    new_jumlah = ""
                    new_catatan = ""


                    if str(request.POST["berat"]) == "":
                        new_berat = str(temp_data[0][5])
                    else:
                        new_berat = str(request.POST["berat"])

trigger2/templates/trigger2/create-item.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>ITEM SUMBER DAYA</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM TAMBAH ITEM</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger2:create_item' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Kode</div>
        <div class="form-group">
          <input type="text" name="kode" value="{{request.POST.kode}}" class="form-width form-control" placeholder="Kode" required>
        </div>
        <div class="pb-1">Username Supplier</div>
        <div class="form-group">
          <input type="text" name="user_supplier" value="{{request.POST.user_supplier}}" class="form-width form-control" placeholder="Supplier" required>
        </div>
        <div class="pb-1">Nama</div>
        <div class="form-group">
          <input type="text" name="nama" value="{{request.POST.nama}}" class="form-width form-control" placeholder="Nama" required>
        </div>
        <div class="pb-1">Harga</div>
        <div class="form-group">
          <input type="text" name="harga" value="{{request.POST.harga}}" class="form-width form-control" placeholder="Harga Satuan" required>
        </div>
        <div class="pb-1">Berat Maksimum</div>
        <div class="form-group">
          <input type="text" name="berat" value="{{request.POST.berat}}" class="form-width form-control" placeholder="Berat Satuan" required>
        </div>
        <div class="pb-1">Kode Tipe Item</div>
        <select id="kode_item" name="kode_item" required>
            <option value="">Choose a code</option>
            {% for kode_item in code %}
                <option value="{{kode_item}}">{{kode_item}}</option>
            {% endfor %}
        </select>  
        {% comment %} <div class="form-group">
          <input type="text" name="kode_item" value="{{request.POST.kode_item}}" class="form-width form-control" placeholder="Kode Tipe Item" required>
        </div> {% endcomment %}

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Register</button>
            <a href='{% url "trigger4:kendaraan" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger2/templates/trigger2/create-permohonan.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>PERMOHONAN SUMBER DAYA</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM CREATE PSD</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger2:create_permohonan' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        
        <div class="pb-1">Petugas Faskes</div>
        <div class="form-group">
          <input type="text" name="petugas" value="{{request.POST.petugas}}" class="form-width form-control" placeholder="Petugas Faskes" required>
        </div>
        
        <div class="pb-1">Kode Item</div>
        <select id="kode_item" name="kode_item" required>
            <option value="">Choose a code</option>
            {% for kode_item in code %}
                <option value="{{kode_item}}">{{kode_item}}</option>
            {% endfor %}
        </select>  

        <div class="pb-1">Berat Item</div>
        <div class="form-group">
          <input type="text" name="berat" value="{{request.POST.berat}}" class="form-width form-control" placeholder="Berat Item" required>
        </div>

        <div class="pb-1">Jumlah Item</div>
        <div class="form-group">
          <input type="text" name="jumlah" value="{{request.POST.jumlah}}" class="form-width form-control" placeholder="Jumlah Item" required>
        </div>

        <div class="pb-1">Catatan</div>
        <div class="form-group">
          <input type="text" name="catatan" value="{{request.POST.catatan}}" class="form-width form-control" placeholder="Catatan">
        </div>

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Register</button>
            <a href='{% url "trigger4:kendaraan" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger2/templates/trigger2/create-riwayat.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>RIWAYAT STATUS PERMOHONAN SUMBER DAYA</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM CREATE RIWAYAT</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger2:create_riwayat' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        
        <div class="pb-1">Nomor Riwayat</div>
        <div class="form-group">
          <input type="text" name="nomor" value="{{request.POST.nomor}}" class="form-width form-control" placeholder="Nomor Riwayat" required>
        </div>

        <div class="pb-1">Username Admin</div>
        <div class="form-group">
          <input type="text" name="admin" value="{{request.POST.admin}}" class="form-width form-control" placeholder="Username Admin" required>
        </div>

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Register</button>
            <a href='{% url "trigger2:riwayat_permohonan_sumber_daya" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger2/templates/trigger2/item-sumber-daya.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Item Sumber Daya</h1>
    <p class="lead">Melihat Item Sumber Daya</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
    
    {% if request.session.pengguna and request.session.role == "supplier"%}
        <a href="{% url 'trigger2:create_item' %}"><u>Tambahkan Item</u></a>
        <br>
        <a href="{% url 'trigger2:update_item' %}"><u>Update Item</u></a>
        <br>
        <a href="{% url 'trigger2:delete_item' %}"><u>Delete Item</u></a>
    {% elif request.session.pengguna and request.session.role == "admin_satgas"%}
    {% else %}
    {% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar Item Sumber Daya</h3>
      <br>
      <input type="text" id="myInput" placeholder="Search for names.." title="Type in a name">
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>Kode</th>
                    <th>Supplier</th>
                    <th>Nama</th>
                    <th>Harga Satuan</th>
                    <th>Berat Satuan</th>
                    <th>Kode Tipe Item</th>
                    {% if request.session.pengguna and request.session.role == "supplier"%}
                        <th>Update/Delete</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for kode, supply, nama, harga, berat, kti in items %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ kode }}</td>
                        <td>{{ supply }}</td>
                        <td>{{ nama }}</td>
                        <td>{{ harga }}</td>
                        <td>{{ berat }}</td>
                        <td>{{ kti }}</td>
                        {% if request.session.pengguna and request.session.role == "supplier"%}
                        <td>
                            <a href="{% url 'trigger2:update_item' %}"><u>Update</u></a>
                            <a href="{% url 'trigger2:delete_item' %}"><u>Delete</u></a>
                        </td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}

trigger2/templates/trigger2/permohonan-sumber-daya.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Permohonan Sumber Daya Faskes</h1>
    <p class="lead">Melihat Daftar Permohonan</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
    
    {% if request.session.pengguna and request.session.role == "petugas_faskes"%}
        <a href="{% url 'trigger2:create_permohonan' %}"><u>Tambahkan Permohonan</u></a>
        <br>
        <a href="{% url 'trigger2:update_permohonan' %}"><u>Update Permohonan</u></a>
        <br>
        <a href="{% url 'trigger2:delete_permohonan' %}"><u>Delete Permohonan</u></a>
    {% elif request.session.pengguna and request.session.role == "admin_satgas"%}
    {% else %}
    {% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar Permohonan Sumber Daya</h3>
      <br>
      <input type="text" id="myInput" placeholder="Search for names.." title="Type in a name">
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>Nomor Transaksi</th>
                    <th>Petugas Faskes</th>
                    <th>Catatan</th>
                    <th>Tanggal</th>
                    <th>Total Item</th>
                    <th>Total Berat</th>
                    
                    {% if request.session.pengguna and request.session.role == "petugas_faskes"%}
                        <th>Update/Delete</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for no , username , catatan, tgl, ti, tb in psd %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ no }}</td>
                        <td>{{ username }}</td>
                        <td>{{ catatan }}</td>
                        <td>{{ tgl }}</td>
                        <td>{{ ti }}</td>
                        <td>{{ tb }}</td>
                        {% if request.session.pengguna and request.session.role == "petugas_faskes"%}
                        <td>
                            <a href="{% url 'trigger2:update_permohonan' %}"><u>Update</u></a>
                            <a href="{% url 'trigger2:delete_permohonan' %}"><u>Delete</u></a>
                        </td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}

trigger2/templates/trigger2/riwayat-status-permohonan.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Riwayat Status Permohonan</h1>
    <p class="lead">Melihat Daftar Riwayat Status Permohonan</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
    
    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
        <a href="{% url 'trigger2:create_riwayat' %}"><u>Buat Riwayat</u></a>
        <br>
        <a href="{% url 'trigger2:proses_riwayat' %}"><u>Proses Riwayat</u></a>
        <br>
        <a href="{% url 'trigger2:proses_riwayat_final' %}"><u>Proses Riwayat PRO</u></a>
    {% elif request.session.pengguna and request.session.role == "petugas_faskes"%}
    {% else %}
    {% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar Riwayat Status Permohonan Sumber Daya</h3>
      <br>
      <input type="text" id="myInput" placeholder="Search for names.." title="Type in a name">
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>Nomor Antrian</th>
                    <th>Kode Status</th>
                    <th>Status</th>
                    <th>Admin</th>
                    <th>Tanggal</th>
                    
                    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
                        <th>Proses</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for no , kode , admin, tgl,status in riwayats %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ no }}</td>
                        <td>{{ kode }}</td>
                        <td>{{ status }}</td>
                        <td>{{ admin }}</td>
                        <td>{{ tgl }}</td>
                        {% if request.session.pengguna and request.session.role == "admin_satgas" and kode == "REQ" %}
                        <td>
                            <a href="{% url 'trigger2:proses_riwayat' %}"><u>Proses</u></a>
                        </td>
                        {% elif request.session.pengguna and request.session.role == "admin_satgas" and kode == "PRO" %}
                        <td>
                            <a href="{% url 'trigger2:proses_riwayat_final' %}"><u>Proses</u></a>
                        </td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}