home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('logging-in/', include('login_feature.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
]

trigger3/urls.py
from django.urls import path

from . import views

app_name = 'trigger3'

urlpatterns = [
    path('', views.index, name='index'),
    path('read-psd', views.read_psd, name='read_psd'),
    path('read-psd-adminsatgas', views.read_psd_adminsatgas, name='read_psd_adminsatgas'),
    path('read-psd-supplier', views.read_psd_supplier, name='read_psd_supplier'),
    path('psd', views.psd, name='psd'),
    path('create-psd', views.create_psd, name='create_psd'),
    path('tambah-psd', views.tambah_psd, name='tambah_psd'),
    path('tampil-update-psd/<int:no_pesanan>', views.tampil_update_psd, name='tampil_update_psd'),
    path('update-psd/<int:no_pesanan>', views.update_psd, name='update_psd'),
    path('delete-psd/<int:no_pesanan>', views.delete_psd, name='delete_psd'),
    path('rspsd', views.rspsd, name='rspsd'),
    path('read-rspsd/<int:no_pesanan>', views.read_rspsd, name='read_rspsd'),
    path('create-status/<int:no_pesanan>', views.create_status, name='create_status'),
    path('sfk-adminsatgas', views.sfk_adminsatgas, name='sfk_adminsatgas'),
    path('sfk-petugasfaskes', views.sfk_petugas, name='sfk_petugas'),
    path('sfk', views.sfk, name='sfk'),
    path('create-sfk', views.create_sfk, name='create_sfk'),
    path('tampil-update-sfk/<str:kode_faskes>/<str:item_sumber_daya>', views.tampil_update_sfk, name='tampil_update_sfk'),
    path('update-sfk', views.update_sfk, name='update_sfk'),
    path('delete-sfk/<str:kode_faskes>/<str:item_sumber_daya>', views.delete_sfk, name='delete_sfk'),
    path('detail-psd/<int:no_pesanan>', views.detail_psd, name='detail_psd')
]

trigger3/models.py
from django.db import models

# Create your models here.

trigger3/views.py
from django.shortcuts import render, redirect
from django.db import connection, IntegrityError
from django.db.utils import InternalError
from django.contrib import messages
from datetime import datetime, date
import random


def index(request):
    context = {
        "role" : request.session["role"]
    }

    return render(request, 'trigger3/index.html', context)

def rspsd(request):
    response = {}
    response['rsp'] = []
    with connection.cursor() as cursor:
        cursor.execute(f"""SELECT DISTINCT ON (no_pesanan) kode_status_pesanan, no_pesanan, username_supplier, tanggal 
                       FROM RIWAYAT_STATUS_PESANAN""")
        rsp = cursor.fetchall()
        for i in range(len(rsp)):
            response['rsp'].append([
                rsp[i][0],
                rsp[i][1],
                rsp[i][2],
                rsp[i][3],
            ])
    return render(request, 'trigger3/rspsd.html', response)
    
def read_rspsd(request, no_pesanan):
    response = {}
    response['rsp'] = []
    with connection.cursor() as cursor:
        cursor.execute(f"""SELECT * FROM HISTORY_STATUS_PESANAN WHERE no_pesanan={no_pesanan}
                       ORDER BY tanggal DESC""")
        rsp = cursor.fetchall()
        for i in range(len(rsp)):
            response['rsp'].append([
                rsp[i][0],
                rsp[i][1],
                rsp[i][2],
                rsp[i][3],
            ])
    return render(request, 'trigger3/rsp.html', response)

def create_status(request, no_pesanan):
    response = {}
    if request.POST.get('process', False) == "REQ-SUP":
        try:
            with connection.cursor() as cursor:
                cursor.execute(f"""UPDATE RIWAYAT_STATUS_PESANAN SET kode_status_pesanan='PRO-SUP', no_pesanan={no_pesanan},
                               username_supplier='{request.session['pengguna']}', tanggal='{date.today()}'
                               WHERE no_pesanan={no_pesanan} AND kode_status_pesanan='REQ-SUP'""")
                
                cursor.execute(f"""INSERT INTO HISTORY_STATUS_PESANAN (kode_status_pesanan, no_pesanan, username_supplier, tanggal)
                            VALUES ('PRO-SUP', {no_pesanan}, '{request.session['pengguna']}', '{datetime.now()}')""")
                
                messages.add_message(request, messages.SUCCESS, "Berhasil menambah riwayat status pesanan")
            
            return redirect('trigger3:read_rspsd', no_pesanan=no_pesanan)
        except InternalError:
            messages.add_message(request, messages.WARNING, "Database sudah penuh")
        except:
            messages.add_message(request, messages.WARNING, "Ada gangguan, mohon mencoba lain kali")
    elif request.POST.get('reject', False) == "REQ-SUP":
        try:
            with connection.cursor() as cursor:
                cursor.execute(f"""UPDATE RIWAYAT_STATUS_PESANAN SET kode_status_pesanan='REJ-SUP', no_pesanan={no_pesanan},
                               username_supplier='{request.session['pengguna']}', tanggal='{date.today()}'
                               WHERE no_pesanan={no_pesanan} AND kode_status_pesanan='REQ-SUP'""")
                
                cursor.execute(f"""INSERT INTO HISTORY_STATUS_PESANAN (kode_status_pesanan, no_pesanan, username_supplier, tanggal)
                            VALUES ('REJ-SUP', {no_pesanan}, '{request.session['pengguna']}', '{datetime.now()}')""")
                
                messages.add_message(request, messages.SUCCESS, "Berhasil menambah riwayat status pesanan")
                return redirect('trigger3:read_rspsd', no_pesanan=no_pesanan)
        except InternalError:
            messages.add_message(request, messages.WARNING, "Database sudah penuh")
        except:
            messages.add_message(request, messages.WARNING, "Ada gangguan, mohon mencoba lain kali")
    elif request.POST.get('selesai-dm', False) == "PRO-SUP":
        try:
            with connection.cursor() as cursor:
                cursor.execute(f"""UPDATE RIWAYAT_STATUS_PESANAN SET kode_status_pesanan='MAS-SUP', no_pesanan={no_pesanan},
                               username_supplier='{request.session['pengguna']}', tanggal='{date.today()}'
                               WHERE no_pesanan={no_pesanan} AND kode_status_pesanan='PRO-SUP'""")
                
                cursor.execute(f"""INSERT INTO HISTORY_STATUS_PESANAN (kode_status_pesanan, no_pesanan, username_supplier, tanggal)
                            VALUES ('MAS-SUP', {no_pesanan}, '{request.session['pengguna']}', '{datetime.now()}')""")
                
                messages.add_message(request, messages.SUCCESS, "Berhasil menambah riwayat status pesanan")
                return redirect('trigger3:read_rspsd', no_pesanan=no_pesanan)
        except InternalError:
            messages.add_message(request, messages.WARNING, "Database sudah penuh")
        except:
            messages.add_message(request, messages.WARNING, "Ada gangguan, mohon mencoba lain kali")
    elif request.POST.get('selesai', False) == "PRO-SUP":
        try:
            with connection.cursor() as cursor:
                cursor.execute(f"""UPDATE RIWAYAT_STATUS_PESANAN SET kode_status_pesanan='FIN-SUP', no_pesanan={no_pesanan},
                               username_supplier='{request.session['pengguna']}', tanggal='{date.today()}'
                               WHERE no_pesanan={no_pesanan} AND kode_status_pesanan='PRO-SUP'""")

                cursor.execute(f"""INSERT INTO HISTORY_STATUS_PESANAN (kode_status_pesanan, no_pesanan, username_supplier, tanggal)
                            VALUES ('FIN-SUP', {no_pesanan}, '{request.session['pengguna']}', '{datetime.now()}')""")
                
                messages.add_message(request, messages.SUCCESS, "Berhasil menambah riwayat status pesanan")
                return redirect('trigger3:read_rspsd', no_pesanan=no_pesanan)
        except InternalError:
            messages.add_message(request, messages.WARNING, "Database sudah penuh")
        except:
            messages.add_message(request, messages.WARNING, "Ada gangguan, mohon mencoba lain kali")
            
    return render(request, 'trigger3/rsp.html', response)

def read_psd(request):
    response = {}
    response['psd'] = []
    with connection.cursor() as cursor:
        cursor.execute(f"""SELECT DISTINCT ON (no_pesanan) no_pesanan, username_admin_satgas, 
                       t.tanggal, total_berat, total_item, total_harga, kode_status_pesanan 
                       FROM TRANSAKSI_SUMBER_DAYA t, PESANAN_SUMBER_DAYA p, RIWAYAT_STATUS_PESANAN r;""")
        psd = cursor.fetchall()
        for i in range(len(psd)):
            response['psd'].append([
                psd[i][0],
                psd[i][1],
                psd[i][2],
                psd[i][3],
                psd[i][4],
                psd[i][5],
                psd[i][6],
            ])
    return render(request, 'trigger3/read-psd.html', response)

def read_psd_adminsatgas(request):
    response = {}
    response['psd'] = []
    with connection.cursor() as cursor:
        cursor.execute(f"""
                       SELECT DISTINCT ON (no_pesanan) no_pesanan, username_admin_satgas, 
                       t.tanggal, total_berat, total_item, total_harga, kode_status_pesanan, username_supplier 
                       FROM TRANSAKSI_SUMBER_DAYA t, PESANAN_SUMBER_DAYA p, RIWAYAT_STATUS_PESANAN r
                       WHERE username_admin_satgas='{request.session['pengguna']}'""")
        psd = cursor.fetchall()
        for i in range(len(psd)):
            response['psd'].append([
                psd[i][0],
                psd[i][1],
                psd[i][2],
                psd[i][3],
                psd[i][4],
                psd[i][5],
                psd[i][6],
                psd[i][7],
            ])
    return render(request, 'trigger3/read-psd.html', response)

def read_psd_supplier(request):
    response = {}
    response['psd'] = []
    with connection.cursor() as cursor:
        cursor.execute(f"""
                       SELECT DISTINCT ON (no_pesanan) no_pesanan, username_admin_satgas, 
                       t.tanggal, total_berat, total_item, total_harga, kode_status_pesanan, username_supplier 
                       FROM TRANSAKSI_SUMBER_DAYA t, PESANAN_SUMBER_DAYA p, RIWAYAT_STATUS_PESANAN r
                       WHERE username_supplier='{request.session['pengguna']}'""")
        psd = cursor.fetchall()
        for i in range(len(psd)):
            response['psd'].append([
                psd[i][0],
                psd[i][1],
                psd[i][2],
                psd[i][3],
                psd[i][4],
                psd[i][5],
                psd[i][6],
                psd[i][7],
            ])
    return render(request, 'trigger3/read-psd.html', response)

def psd(request):
    response = {}
    with connection.cursor() as cursor:
        cursor.execute(f"""SELECT username FROM SUPPLIER""")
        suppliers = cursor.fetchall()
        for i in range(len(suppliers)):
            suppliers[i] = suppliers[i][0]
        response['suppliers'] = suppliers
    return render(request, 'trigger3/psd.html', response)

def create_psd(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""
                    SELECT kode FROM ITEM_SUMBER_DAYA
                    WHERE username_supplier = '{request.POST["supplier"]}'""")

                kodes = cursor.fetchall()
                idnom = 1
                
                for i in range(len(kodes)):
                    kodes[i] = kodes[i][0]
                    
                response['kodes'] = kodes
                response['no_urut'] = idnom
                response['supplier'] = request.POST["supplier"]

                # return render(request, 'trigger3/create-psd.html', response)

trigger3/templates/trigger3/create-psd.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>PESANAN SUMBER DAYA</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM CREATE PESANAN SUMBER DAYA</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger3:tambah_psd' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
		<div class="pb-1">Supplier</div>
        <input class="form-control" type="text" value="{{supplier}}" disabled readonly>
		<input class="form-control" type="hidden" name="supplier" value="{{supplier}}">

        <div class="pb-1">No. Urut</div>
        <input class="form-control" type="text" value="{{no_urut}}" disabled readonly>
		<input class="form-control" type="hidden" name="no_urut" value="{{no_urut}}">

		<div class="pb-1">Kode Item</div>
        <div class="form-group">
			<select id="kode_item" name="kode_item">
			  <option value="">Choose Item Code</option>
			  {% for kode in kodes %}
				  <option value="{{kode}}">{{kode}}</option>
			  {% endfor %}
			</select>
		</div>

		<div class="pb-1">Jumlah Item</div>
        <div class="form-group">
          <input type="number" name="jumlah_item" class="form-width form-control" required>
        </div>
        
        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
    </form>

    {% for item in items %}
	{{ item }}
	{% endfor %}
</div>

{% endblock %}

trigger3/templates/trigger3/create-sfk.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>PESANAN SUMBER DAYA</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM CREATE STOK FASKES</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger3:create_sfk' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Kode Faskes</div>
        <div class="form-group">
          <select id="kode_faskes" name="kode_faskes">
            <option value="">Pilih Kode Faskes</option>
            {% for kode in kodes %}
                <option value="{{kode}}">{{kode}}</option>
            {% endfor %}
          </select>
        </div>

		<div class="pb-1">Kode Item</div>
        <div class="form-group">
          <select id="item_codes" name="kode_item">
            <option value="">Pilih Kode Item</option>
            {% for code in item_codes %}
                <option value="{{code}}">{{code}}</option>
            {% endfor %}
          </select>
        </div>

		<div class="pb-1">Jumlah</div>
        <div class="form-group">
          <input type="number" name="jumlah" class="form-width form-control" required>
        </div>
        
        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
    </form>

    
</div>

{% endblock %}

trigger3/templates/trigger3/index.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>STOK DAN PESANAN</title>
{% endblock meta %}
{% block content %}
<div class="jumbotron bg-white text-dark rounded-0 m-0">
    <div class="container">
        <ul class="navbar-nav" style="margin: auto;">
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">
                    <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas" %}
                            <a class="book-link text-light" href="{% url 'trigger3:read_psd_adminsatgas' %}">
                                Pesanan Sumber Daya
                            </a>
                        {% elif request.session.pengguna and role == "supplier" %}
                            <a class="book-link text-light" href="{% url 'trigger3:read_psd_supplier' %}">
                                Pesanan Sumber Daya
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger3:read_psd' %}">
                                Pesanan Sumber Daya
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Pesanan Sumber Daya Faskes</h5>
                                <p class="card-text text-justify">CRUD untuk pengguna admin_satgas serta r untuk pengguna supplier</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">

                     <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "supplier"%}
                            <a class="book-link text-light" href="{% url 'trigger3:rspsd' %}">
                                Riwayat Status Pesanan Sumber Daya
                            </a>
                        {% elif request.session.pengguna and role == "admin_satgas"%}
                            <a class="book-link text-light" href="{% url 'trigger3:rspsd' %}">
                                Riwayat Status Pesanan Sumber Daya
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger3:index' %}">
                                Riwayat Status Pesanan Sumber Daya
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Riwayat Status Pesanan Sumber Daya Faskes</h5>
                                <p class="card-text text-justify">CR untuk pengguna supplier serta r untuk pengguna admin_satgas</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">
                   <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas" %}
                            <a class="book-link text-light" href="{% url 'trigger3:sfk_adminsatgas' %}">
                                Stok Faskes
                            </a>
                        {% elif request.session.pengguna and role == "petugas_faskes" %}
                            <a class="book-link text-light" href="{% url 'trigger3:sfk_petugas' %}">
                                Stok Faskes
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger3:index' %}">
                                Stok Faskes
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Stok Faskes</h5>
                                <p class="card-text text-justify">CRUD untuk pengguna admin_satgas serta r untuk pengguna petugas_faskes</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

trigger3/templates/trigger3/read-psd.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>PESANAN SUMBER DAYA</title>
{% endblock meta %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Pesanan Sumber Daya</h1>
    <p class="lead">Melihat Pesanan Sumber Daya</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>

	{% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}

    {% endif %}
	{% if request.session.pengguna and request.session.role == "admin_satgas" %}
	<button class="btn btn-light my-1"><a href="{% url 'trigger3:psd' %}">Create Pesanan Sumber Daya</a></button>
	{% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Pesanan Sumber Daya</h3>
      <br>
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>No. Pesanan</th>
                    <th>Petugas Satgas</th>
					<th>Tanggal</th>
					<th>Total Berat</th>
					<th>Total Item</th>
                    <th>Total Harga</th>
					<th>Status</th>
					<th>Action</th>
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for no_pesanan, username_admin_satgas, tanggal, total_berat, total_item, total_harga, kode_status_pesanan, username_supplier in psd %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ no_pesanan }}</td>
                        <td>{{ username_admin_satgas}}</td>
						<td>{{ tanggal }}</td>
						<td>{{ total_berat }}</td>
						<td>{{ total_item }}</td>
                        <td>{{ total_harga }}</td>
						<td>{{ kode_status_pesanan }}</td>
						<td>
						{% if request.session.pengguna and request.session.role == "admin_satgas" and kode_status_pesanan == "REQ-SUP" %}
						<form method="POST" action="{% url 'trigger3:tampil_update_psd' no_pesanan %}">
							{% csrf_token %}
							<button class="btn btn-light my-1" type="submit" name="supplier" value="{{ username_supplier }}">Update</button>
						</form>
						<form method="POST" action="{% url 'trigger3:delete_psd' no_pesanan %}">
							{% csrf_token %}
							<button class="btn btn-danger my-1" type="submit" name="no_pesanan" value="{{ no_pesanan }}">Delete</button>
						</form>
						{% elif request.session.pengguna and request.session.role == "supplier" and kode_status_pesanan == "REQ-SUP" %}
						<form method="POST" action="{% url 'trigger3:create_status' no_pesanan %}">
							{% csrf_token %}
							<button class="btn btn-primary my-1" type="submit" name="reject" value="{{ kode_status_pesanan }}">Reject</button>
							<button class="btn btn-primary my-1" type="submit" name="process" value="{{ kode_status_pesanan }}">Process</button>
						</form>
						{% elif request.session.pengguna and request.session.role == "supplier" and kode_status_pesanan == "PRO-SUP" %}
						<form method="POST" action="{% url 'trigger3:create_status' no_pesanan %}">
							{% csrf_token %}
							<button class="btn btn-primary my-1" type="submit" name="selesai-dm" value="{{ kode_status_pesanan }}">Selesai dengan masalah</button>
							<button class="btn btn-primary my-1" type="submit" name="selesai" value="{{ kode_status_pesanan }}">Selesai</button>
						</form>
						{% endif %}
						{% if request.session.pengguna and request.session.role == "admin_satgas" or request.session.role == "supplier" %}
							<button class="btn btn-light my-1"><a href="{% url 'trigger3:detail_psd' no_pesanan %}">Detail</a></button>
							<button class="btn btn-light my-1"><a href="{% url 'trigger3:read_rspsd' no_pesanan %}">Riwayat Status</a></button>
						{% endif %}
						</td>
					</tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}

trigger3/templates/trigger3/read-sfk.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>PESANAN SUMBER DAYA</title>
{% endblock meta %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Stok Faskes</h1>
    <p class="lead">Melihat Stok Faskes</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>

	{% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

	{% if request.session.pengguna and request.session.role == "admin_satgas" %}
	<button class="btn btn-light my-1"><a href="{% url 'trigger3:sfk' %}">Create Stok Faskes</a></button>
	{% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Stok Faskes</h3>
      <br>
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>Kode Faskes</th>
                    <th>Nama Faskes</th>
					<th>Item Sumber Daya</th>
					<th>Jumlah</th>
					<th>Action</th>
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for kode_faskes, nama_tipe, item_sumber_daya, jumlah in sfk %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ kode_faskes }}</td>
                        <td>{{ nama_tipe }}</td>
						<td>{{ item_sumber_daya }}</td>
						<td>{{ jumlah }}</td>
						<td>
						{% if request.session.pengguna and request.session.role == "admin_satgas" %}
						<form method="POST" action="{% url 'trigger3:tampil_update_sfk' kode_faskes item_sumber_daya %}">
							{% csrf_token %}
							<button class="btn btn-light my-1" type="submit" name="stok_faskes" value="{{ stok_faskes }}">Update</button>
						</form>
						<form method="POST" action="{% url 'trigger3:delete_sfk' kode_faskes item_sumber_daya %}">
							{% csrf_token %}
							<button class="btn btn-danger my-1" type="submit" name="stok_faskes" value="{{ stok_faskes }}">Delete</button>
						</form>
						{% endif %}
						</td>
					</tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}