home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('logging-in/', include('login_feature.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
]

trigger4/urls.py
from django.urls import path

from . import views

app_name = 'trigger4'

urlpatterns = [
    path('', views.index, name='index'),
    path('lokasi', views.lokasi, name='lokasi'),
    path('form-lokasi', views.form_lokasi, name='form_lokasi'),
    path('update-lokasi', views.update_lokasi, name='update_lokasi'),
    path('batch-pengiriman', views.batch_pengiriman, name='batch_pengiriman'),
    path('create-batch', views.create_batch, name='create_batch'),
    path('detail-batch', views.detail_batch, name='detail_batch'),
    path('kendaraan', views.kendaraan, name='kendaraan'),
    path('create-kendaraan', views.create_kendaraan, name='create_kendaraan'),
    path('update-kendaraan', views.update_kendaraan, name='update_kendaraan'),
    path('delete-kendaraan', views.delete_kendaraan, name='delete_kendaraan'),
]

trigger4/models.py
from django.db import models

# Create your models here.

trigger4/views.py
from django.shortcuts import render, redirect
from django.db import connection, IntegrityError
from django.db.utils import InternalError
from django.contrib import messages
from datetime import datetime
import random

# Create your views here.
def index(request):
    # context = {}
    # try:
    context = {
        "role" : request.session["role"]
    }
    # except:
    #     messages.add_message(request, messages.WARNING, f"Anda belum login")

    return render(request, 'trigger4/index.html', context)


def lokasi(request):
    response = {}
    response['location'] = []
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM LOKASI")
        loc = cursor.fetchall()
        for i in range(len(loc)):
            # cursor.execute("SELECT ID FROM TEMA WHERE ID_event = %s", [Anevent[i][0]])
            # loc_tuple = cursor.fetchall()
            # locations = []
            # for louc in loc_tuple:
            #     locations.append(louc[0])

            response['location'].append([
                loc[i][0],
                loc[i][1],
                loc[i][2],
                loc[i][3],
                loc[i][4],
                loc[i][5]
            ]) 
    return render(request, 'trigger4/lokasi.html', response)

def update_lokasi(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""
                    SELECT * FROM LOKASI WHERE id='{request.POST["id"]}'""")
                idnom = len(cursor.fetchall())

                if (idnom > 0):
                # cursor.execute(f"""
                #     UPDATE LOKASI SET id = '{request.POST["id"]}', provinsi = '{request.POST["provinsi"]}',
                #     kabkot = '{request.POST["kabkot"]}', kecamatan = '{request.POST["kecamatan"]}',
                #     kelurahan = '{request.POST["kelurahan"]}', jalan_no = '{request.POST["jalan"]}',
                #     id_tipe = '{kode}'
                #     WHERE id_event = '{id_event}'
                # """)
                    new_provinsi = ""
                    new_kabkot = ""
                    new_kecamatan = ""
                    new_kelurahan = ""
                    new_jalan = ""

                    cursor.execute(f"""
                            SELECT * FROM LOKASI WHERE id='{request.POST["id"]}'""")
                    temp_data = cursor.fetchall()
                
                    if str(request.POST["provinsi"]) == "":
                        new_provinsi = str(temp_data[0][1])
                    else:
                        new_provinsi = str(request.POST["provinsi"])

                    if str(request.POST["kabkot"]) == "":
                        new_kabkot = str(temp_data[0][2])
                    else:
                        new_kabkot = str(request.POST["kabkot"])

                    if str(request.POST["kecamatan"]) == "":
                        new_kecamatan = str(temp_data[0][3])
                    else:
                        new_kecamatan = str(request.POST["kecamatan"])

                    if str(request.POST["kelurahan"]) == "":
                        new_kelurahan = str(temp_data[0][4])
                    else:
                        new_kelurahan = str(request.POST["kelurahan"])

                    if str(request.POST["jalan"]) == "":
                        new_jalan = str(temp_data[0][5])
                    else:
                        new_jalan = str(request.POST["jalan"])

                    cursor.execute(f"""
                        UPDATE LOKASI SET id='{request.POST["id"]}', provinsi='{new_provinsi}', 
                        kabkot='{new_kabkot}', kecamatan='{new_kecamatan}', kelurahan='{new_kelurahan}'
                        , jalan_no='{new_jalan}' WHERE id='{request.POST["id"]}'""")
                    messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                    return redirect("trigger4:lokasi")
                else:
                    messages.add_message(request, messages.WARNING, f"“Data salah")
    
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Data salah")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")
    return render(request, 'trigger4/update-lokasi.html')


def form_lokasi(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""
                    SELECT * FROM LOKASI""")
                idnom = len(cursor.fetchall()) + 1

                # Kalau gak ada PENGGUNA dengan email sama maka lanjut bikinin
                # if (idnom < 10):
                #     cursor.execute(f"""
                #         INSERT INTO LOKASI (id, provinsi, kabkot, kecamatan, kelurahan, jalan_no) VALUES
                #         ('Loc0{idnom}', '{request.POST["provinsi"]}', '{request.POST["kabkot"]}', '{request.POST["kecamatan"]}'
                #         , '{request.POST["kelurahan"]}', '{request.POST["jalan"]}') """)
                # else:
                cursor.execute(f"""
                    INSERT INTO LOKASI (id, provinsi, kabkot, kecamatan, kelurahan, jalan_no) VALUES
                    ('Loc{str(idnom).zfill(2)}', '{request.POST["provinsi"]}', '{request.POST["kabkot"]}', '{request.POST["kecamatan"]}'
                    , '{request.POST["kelurahan"]}', '{request.POST["jalan"]}') """)
                
                # return redirect("")
                messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                return redirect("trigger4:lokasi")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")
    return render(request, 'trigger4/form_lokasi.html')

def batch_pengiriman(request):
    # response = {}
    # response['batches'] = []
    # with connection.cursor() as cursor:
    #     # cursor.execute(f""" SELECT b.no_transaksi_sumber_daya, f.username_petugas, f.kode_faskes_nasional, 
    #     #     t.total_berat, rsp.kode_status_permohonan , rws.kode_status_batch_pengiriman
    #     #     FROM BATCH_PENGIRIMAN AS b
    #     #     JOIN TRANSAKSI_SUMBER_DAYA AS t ON t.nomor = b.no_transaksi_sumber_daya
    #     #     JOIN PERMOHONAN_SUMBER_DAYA_FASKES AS psdf ON psdf.no_transaksi_sumber_daya = t.nomor
    #     #     JOIN RIWAYAT_STATUS_PERMOHONAN AS rsp ON psdf.no_transaksi_sumber_daya = rsp.nomor_permohonan
    #     #     JOIN RIWAYAT_STATUS_PENGIRIMAN AS rws ON b.kode = rws.kode_batch
    #     #     JOIN LOKASI AS l ON b.id_lokasi_tujuan  = l.id
    #     #     JOIN FASKES AS f ON f.id_lokasi = l.id """)
    #     cursor.execute(f""" SELECT * FROM PERMOHONAN_""")
    #     loc = cursor.fetchall()
    #     for i in range(len(loc)):

    #         response['batches'].append([
    #             loc[i][0],
    #             loc[i][1],
    #             loc[i][2],
    #             loc[i][3],
    #             loc[i][4],
    #             loc[i][5],
    #             loc[i][6]
    #         ]) 
    # return render(request, 'trigger4/batch_pengiriman.html', response)
    response = {}
    response['batches'] = []
    with connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT p.no_transaksi_sumber_daya, p.username_petugas_faskes, p.catatan, t.tanggal, t.total_item, t.total_berat, rsp.kode_status_permohonan 
            FROM PERMOHONAN_SUMBER_DAYA_FASKES AS p, TRANSAKSI_SUMBER_DAYA AS t, RIWAYAT_STATUS_PERMOHONAN rsp
            WHERE p.no_transaksi_sumber_daya = t.nomor AND p.no_transaksi_sumber_daya = rsp.nomor_permohonan """)
        fetched = cursor.fetchall()

        for i in range(len(fetched)):
            response['batches'].append([
                fetched[i][0],
                fetched[i][1],
                fetched[i][2],
                fetched[i][3],
                fetched[i][4],
                fetched[i][5],
                fetched[i][6],
            ]) 
    return render(request, 'trigger4/batch_pengiriman.html', response)

def detail_batch(request):
    response = {}
    response['batches'] = []
    with connection.cursor() as cursor:
        cursor.execute(f""" SELECT * FROM BATCH_PENGIRIMAN """)
        loc = cursor.fetchall()
        for i in range(len(loc)):

            response['batches'].append([
                loc[i][0],
                loc[i][1],
                loc[i][2],
                loc[i][3],
                loc[i][4],
                loc[i][5],
                loc[i][6],
                loc[i][7],
            ]) 
    return render(request, 'trigger4/detail-batch.html', response)


def create_batch(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:

                cursor.execute(f"""SELECT * FROM TRANSAKSI_SUMBER_DAYA WHERE nomor={request.POST["no_trans"]}""")
                length = cursor.fetchall()
                if len(length) != 0:
                    new_petugas = ""
                    cursor.execute(f"""
                        SELECT * FROM BATCH_PENGIRIMAN""")
                    idnom = len(cursor.fetchall()) + 1
                    #user_acc = request.session.get("pengguna", False)
                    # user_acc = str(request.session["pengguna"])
                    # cursor.execute(f"""SELECT nomor FROM KENDARAAN WHERE nama = '{request.POST["kendaraan"]}'""")
                    # carz = str(cursor.fetchall())

                    # cursor.execute(f"""
                    #     SELECT * FROM PETUGAS_DISTRIBUSI WHERE username='{request.POST["petugas"]}'""")
                    # idnome = len(cursor.fetchall())

                    # request.POST["nama_admin"]
                    
                    if str(request.POST["petugas"]) == "":

trigger4/templates/trigger4/batch_pengiriman.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Batch Pengiriman</h1>
    <p class="lead">Melihat Batch</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Batch Pengiriman</h3>
      <td><a href="{% url 'trigger4:create_batch' %}">Buat Badge</a></td>
      <br>
      <td><a href="{% url 'trigger4:detail_batch' %}">Detail Badge</a></td>
      {% comment %} ^tambahan {% endcomment %}
      {% comment %} a {% endcomment %}
      <br>
      <input type="text" id="myInput" placeholder="Search for names.." title="Type in a name">
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    {% comment %} <th>No Transaksi</th>
                    <th>Petugas FASKES</th>
                    <th>Faskes</th>
                    <th>Total Berat</th>
                    <th>Status Permohonan</th>
                    <th>Status Badge</th>
                    <th>Action</th> {% endcomment %}
                    <th>No</th>
                    <th>Nomor Transaksi</th>
                    <th>Petugas Faskes</th>
                    <th>Total Item</th>
                    <th>Total Berat</th>
                    <th>Status</th>
                    <th>Validasi/Detail</th>
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for no, pf, cat, tgl, ti, tb, stt in batches %}
                      <tr class="table-light">
                          <td>{{ forloop.counter }}</td>
                          <td>{{ no }}</td>
                          <td>{{ pf }}</td>
                          <td>{{ ti }}</td>
                          <td>{{ tb }}</td>
                          <td>{{ stt }}</td>
                          {% comment %} <td>{{ sb }}</td> {% endcomment %}
                          {% if stt == "PRO" %}
                            <td><a href="{% url 'trigger4:create_batch' %}">Buat Badge</a></td>
                          {% elif  stt == "FIN" %}
                            <td><a href="{% url 'trigger4:detail_batch' %}">Detail</a></td>
                          {% elif  stt == "MAS" %}
                            <td><a href="{% url 'trigger4:detail_batch' %}">Detail</a></td>
                          {% endif %}
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}

trigger4/templates/trigger4/create-kendaraan.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>KENDARAAN</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM TAMBAH KENDARAAN</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger4:create_kendaraan' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Nomor Kendaraan</div>
        <div class="form-group">
          <input type="text" name="nomor_kendaraan" value="{{request.POST.nomor_kendaraan}}" class="form-width form-control" placeholder="Nomor Kendaraan" required>
        </div>
        <div class="pb-1">Nama</div>
        <div class="form-group">
          <input type="text" name="nama" value="{{request.POST.nama}}" class="form-width form-control" placeholder="Nama" required>
        </div>
        <div class="pb-1">Jenis Kendaraan</div>
        <div class="form-group">
          <input type="text" name="jenis" value="{{request.POST.jenis}}" class="form-width form-control" placeholder="Contoh : Sedan, Truk, dll" required>
        </div>
        <div class="pb-1">Berat Maksimum</div>
        <div class="form-group">
          <input type="text" name="berat" value="{{request.POST.berat}}" class="form-width form-control" placeholder="Berat Maksimum" required>
        </div>
    

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Register</button>
            <a href='{% url "trigger4:kendaraan" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger4/templates/trigger4/create_batch.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>LOKASI</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM CREATE BATCH</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger4:create_batch' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Nama Admin</div>
        <div class="form-group">
          <input type="username" name="nama_admin" value="{{request.POST.nama_admin}}" class="form-width form-control" aria-describedby="emailHelp" placeholder="Nama Admin" required>
        </div>
        <div class="pb-1">Nomor Transaksi</div>
        <div class="form-group">
          <input type="username" name="no_trans" value="{{request.POST.no_trans}}" class="form-width form-control" aria-describedby="emailHelp" placeholder="No Transaksi" required>
        </div>
        <div class="pb-1">Petugas</div>
        <div class="form-group">
          <input type="text" name="petugas" value="{{request.POST.petugas}}" class="form-width form-control" placeholder="Petugas (Not Required)">
        </div>
         {% comment %} <div class="pb-1">Kendaraan</div>
        <div class="form-group">
          <input type="username" name="kendaraan" value="{{request.POST.kendaraan}}" class="form-width form-control" placeholder="Mobil" required>
        </div> 
        <div class="pb-1">Petugas</div>
        <div class="form-group">
          <input type="text" name="petugas" value="{{request.POST.petugas}}" class="form-width form-control" placeholder="Petugas" required>
        </div>
        <div class="pb-1">Asal</div>
        <div class="form-group">
          <input type="text" name="asal" value="{{request.POST.asal}}" class="form-width form-control" placeholder="Asal" required>
        </div>
        <div class="pb-1">Tujuan</div>
        <div class="form-group">
          <input type="text" name="tujuan" value="{{request.POST.tujuan}}" class="form-width form-control" placeholder="Tujuan" required>
        </div> {% endcomment %}
        <div class="pb-1">Tanda Terima</div>
        <div class="form-group">
          <input type="username" name="tterima" value="{{request.POST.tterima}}" class="form-width form-control" placeholder="Tanda Terima" required>
        </div>
    

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Register</button>
            <a href='{% url "home:index" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger4/templates/trigger4/delete-kendaraan.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>KENDARAAN</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM DELETE KENDARAAN</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger4:delete_kendaraan' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Nomor Kendaraan</div>
        <div class="form-group">
          <input type="text" name="nomor_kendaraan" value="{{request.POST.nomor_kendaraan}}" class="form-width form-control" placeholder="Nomor Kendaraan" required>
        </div>
    

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Hapus</button>
            <a href='{% url "trigger4:kendaraan" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger4/templates/trigger4/index.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>PENGIRIMAN</title>
{% endblock meta %}
{% block content %}
<div class="jumbotron bg-white text-dark rounded-0 m-0">
    <div class="container">
        <ul class="navbar-nav" style="margin: auto;">
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">
                    <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas"%}
                            <a class="book-link text-light" href="{% url 'trigger4:kendaraan' %}">
                                Kendaraan
                            </a>
                        {% elif request.session.pengguna and role == "petugas_distribusi"%}
                            <a class="book-link text-light" href="{% url 'trigger4:kendaraan' %}">
                                Kendaraan
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger4:index' %}">
                                Kendaraan
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Kendaraan</h5>
                                <p class="card-text text-justify">CRUD untuk pengguna admin_satgas serta r untuk pengguna petugas_distribusi</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">
                    <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas"%}
                            <a class="book-link text-light" href="{% url 'trigger4:batch_pengiriman' %}">
                                Buat Batch Pengiriman
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger4:index' %}">
                                    Buat Batch Pengiriman
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Membuat Batch Pengiriman</h5>
                                <p class="card-text text-justify">Oleh admin satgas saja</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">
                    <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas"%}
                            <a class="book-link text-light" href="{% url 'trigger4:lokasi' %}">
                                Daftar Lokasi
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger4:index' %}">
                                Daftar Lokasi
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Lokasi</h5>
                                <p class="card-text text-justify">Oleh admin satgas saja</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

trigger4/templates/trigger4/kendaraan.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Kendaraan</h1>
    <p class="lead">Melihat Kendaraan</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
    
    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
        <a href="{% url 'trigger4:create_kendaraan' %}"><u>Tambahkan Kendaraan</u></a>
        <br>
        <a href="{% url 'trigger4:update_kendaraan' %}"><u>Update Kendaraan</u></a>
        <br>
        <a href="{% url 'trigger4:delete_kendaraan' %}"><u>Delete Kendaraan</u></a>
    {% elif request.session.pengguna and request.session.role == "petugas_distribusi"%}
    {% else %}
    {% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar Lokasi</h3>
      <br>
      <input type="text" id="myInput" placeholder="Search for names.." title="Type in a name">
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>No Kendaraan</th>
                    <th>Nama</th>
                    <th>Jenis Kendaraan</th>
                    <th>Berat Maksimum</th>
                    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
                        <th>Update/Delete</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for no_kend, nama, jenis, berat in vehicles %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ no_kend }}</td>
                        <td>{{ nama }}</td>
                        <td>{{ jenis }}</td>
                        <td>{{ berat }}</td>
                        {% if request.session.pengguna and request.session.role == "admin_satgas"%}
                        <td>
                            <a href="{% url 'trigger4:update_kendaraan' %}"><u>Update Kendaraan</u></a>
                            <a href="{% url 'trigger4:delete_kendaraan' %}"><u>Delete Kendaraan</u></a>
                        </td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}

trigger4/templates/trigger4/lokasi.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Lokasi</h1>
    <p class="lead">Melihat lokasi</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <a href="{% url 'trigger4:form_lokasi' %}"><u>Create Lokasi</u></a>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <a href="{% url 'trigger4:form_lokasi' %}"><u>Create Lokasi</u></a>
      <br>
    {% endif %}
    <br>
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar Lokasi</h3>
      <br>
      <input type="text" id="myInput" placeholder="Search for names.." title="Type in a name">
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No</th>
                    <th>ID</th>
                    <th>Provinsi</th>
                    <th>Kabupaten/Kota</th>
                    <th>Kecamatan</th>
                    <th>Kelurahan</th>
                    <th>Jalan</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    {% for id, provinsi, kabkot, kecamatan, kelurahan, jalan in location %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ id }}</td>
                        <td>{{ provinsi }}</td>
                        <td>{{ kabkot }}</td>
                        <td>{{ kecamatan }}</td>
                        <td>{{ kelurahan }}</td>
                        <td>{{ jalan }}</td>
                        <td><a href="{% url 'trigger4:update_lokasi' %}">Update</a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}