home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('logging-in/', include('login_feature.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
]

trigger5/urls.py
from django.urls import path

from . import views

app_name = 'trigger5'

urlpatterns = [
    path('', views.index, name='index'),
    path('faskes', views.faskes, name='faskes'),
    path('create-faskes', views.create_faskes, name='create_faskes'),
    path('update-faskes', views.update_faskes, name='update_faskes'),
    path('delete-faskes', views.delete_faskes, name='delete_faskes'),
    path('warehouse', views.warehouse, name='warehouse'),
    path('create-warehouse', views.create_warehouse, name='create_warehouse'),
    path('update-warehouse', views.update_warehouse, name='update_warehouse'),
    path('delete-warehouse', views.delete_warehouse, name='delete_warehouse'),
    path('batch-pengiriman', views.batch, name='batch'),
    path('batch-lokasi', views.batch_lokasi, name='batch_lokasi'),
    path('detail', views.detail_batch, name='detail_batch')
]

trigger5/models.py
from django.db import models

# Create your models here.

trigger5/views.py
from django.shortcuts import render, redirect
from django.db import connection, IntegrityError
from django.db.utils import InternalError
from django.contrib import messages
from datetime import datetime
import random

# Create your views here.
def index(request):
    context = {
        "role" : request.session["role"]
    }

    return render(request, 'trigger5/index.html', context)
    
def faskes(request):
    response = {}
    response['faskes'] = []
    with connection.cursor() as cursor:
        cursor.execute('''
        SELECT DISTINCT f.kode_faskes_nasional, l.jalan_no, l.kelurahan, l.kecamatan, l.kabkot, l.provinsi, f.username_petugas,  t.nama_tipe
        FROM FASKES f, LOKASI l, TIPE_FASKES t  
        WHERE f.kode_tipe_faskes = t.kode
        AND f.id_lokasi = l.id''')
        fetched = cursor.fetchall()
        for i in range(len(fetched)):
            response['faskes'].append([
                fetched[i][0],
                fetched[i][1] +", "+ fetched[i][2]+", "+fetched[i][3]+", "+fetched[i][4]+", "+fetched[i][5],
                fetched[i][6],
                fetched[i][7],
            ]) 
    return render(request, 'trigger5/faskes.html', response)
 
def create_faskes(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                codelen = len(str(request.POST["kode"])) - 2
                userlen = len(str(request.POST["petugas"])) - 2
                location = str({request.POST["id_loc"]})[2:7]
                codex = str(request.POST["kode"])
                userss = str(request.POST["petugas"])

                cursor.execute(f"""
                    INSERT INTO FASKES (kode_faskes_nasional, id_lokasi, username_petugas, kode_tipe_faskes) VALUES
                    ('{request.POST["codex"]}', '{location}', '{userss}', '{codex}') """)
                # cursor.execute(f"""
                #     INSERT INTO FASKES (kode_faskes_nasional, id_lokasi, username_petugas, kode_tipe_faskes) VALUES
                #     ('{request.POST["kode_faskes_nasional"]}', '{request.POST["id_loc"]}', '{request.POST["petugas"]}', '{request.POST["kode"]}') """)
                
                messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                return redirect("trigger5:faskes")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            # except:
            #     messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")

    else:
        response['id_lokasi'] = []
        response['petugas_faskes'] = []
        response['kode_tipe_faskes'] = []
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM LOKASI")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['id_lokasi'].append(fetched[i][0])
                
            cursor.execute("SELECT * FROM petugas_faskes")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['petugas_faskes'].append(fetched[i][0]) 
                
            cursor.execute("SELECT * FROM tipe_faskes")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['kode_tipe_faskes'].append(fetched[i][0])

    return render(request, 'trigger5/create_faskes.html', response)
 
def update_faskes(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                lenloc = len(str(request.POST["id_loc"])) - 2
                userloc = len(str(request.POST["petugas"])) - 2
                codeloc = len(str(request.POST["kode_faskes_nasional"])) - 2
                codnas = str(request.POST["kode_faskes_nasional"])
                usernames = str(request.POST["petugas"])
                codex = str(request.POST["kode"])

                cursor.execute(f""" 
                    UPDATE FASKES SET 
                        kode_faskes_nasional='{codnas}',
                        id_lokasi='{idloc}',
                        username_petugas='{usernames}',
                        kode_tipe_faskes = '{codex}'
                        WHERE kode_faskes_nasional = '{codnas}'
                    """)
                messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                return redirect("trigger5:faskes")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")

    else:
        response["kode_faskes_nasional"] = []
        response['id_lokasi'] = []
        response['petugas_faskes'] = []
        response['kode_tipe_faskes'] = []
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM faskes")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['kode_faskes_nasional'].append(fetched[i][0]) 

            cursor.execute("SELECT * FROM LOKASI")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['id_lokasi'].append(fetched[i][0])

            cursor.execute("SELECT * FROM petugas_faskes")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['petugas_faskes'].append(fetched[i][0]) 
                
            cursor.execute("SELECT * FROM tipe_faskes")
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['kode_tipe_faskes'].append(fetched[i][0])
    return render(request, 'trigger5/update_faskes.html', response)

def delete_faskes(request):
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                cursor.execute(f"""DELETE FROM FASKES WHERE kode_faskes_nasional='{request.POST["kode_faskes_nasional"]}'""")
                messages.add_message(request, messages.SUCCESS, f"Penghapusan berhasil")
                return redirect("trigger5:faskes")

            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")
    return render(request, 'trigger5/delete_faskes.html')

def warehouse(request):
    response = {}
    response['lokasi'] = []
    with connection.cursor() as cursor:
        cursor.execute('''
        SELECT DISTINCT l.jalan_no, l.kelurahan, l.kecamatan, l.kabkot, l.provinsi
        FROM LOKASI l, WAREHOUSE_PROVINSI w
        WHERE l.id in (SELECT id_lokasi FROM WAREHOUSE_PROVINSI)
        ''')
        
        fetched = cursor.fetchall()
        for i in range(len(fetched)):
            response['lokasi'].append([
                fetched[i][4],
                str(fetched[i][0]).capitalize()+", "+ str(fetched[i][1]).capitalize()+", "+str(fetched[i][2]).capitalize()+", "+str(fetched[i][3]).capitalize()
            ]) 

    return render(request, 'trigger5/warehouse.html', response)
 
def create_warehouse(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                location = str(request.POST["id_lokasi"])
                cursor.execute(f"""SELECT l.provinsi FROM LOKASI l, WAREHOUSE_PROVINSI wp WHERE l.id=wp.id_lokasi AND wp.id_lokasi='{location}' AND l.provinsi='{request.POST["provinsi"]}'""")
                fetched = cursor.fetchall()
                if len(fetched) == 0:
                    cursor.execute(f"""
                        INSERT INTO WAREHOUSE_PROVINSI (id_lokasi) VALUES ('{location}') """)
        
                messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                return redirect("trigger5:warehouse")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"“Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")

    else:
        response['lokasi'] = []
        response['provinsi'] = []
        with connection.cursor() as cursor:
            cursor.execute('''
            SELECT DISTINCT *
            FROM LOKASI 
            ''')
            fetched = cursor.fetchall()
            for i in range(len(fetched)):
                response['lokasi'].append(fetched[i][0]) 
                # response['provinsi'].append([
                #     fetched[i][1],
                # ]) 

    return render(request, 'trigger5/create_warehouse.html', response)
 
def update_warehouse(request):
    response = {}
    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                locawal = str(request.POST["id_lokasi_awal"])#[2:7]
                locganti = str(request.POST["id_lokasi_ganti"])#[2:7]
                cursor.execute(f""" 
                    UPDATE WAREHOUSE_PROVINSI SET 
                        id_lokasi='{locganti}'
                        WHERE id_lokasi = '{locawal}'
                    """)
                messages.add_message(request, messages.SUCCESS, f"Penambahan berhasil")
                return redirect("trigger5:warehouse")
      
            except InternalError:
                messages.add_message(request, messages.WARNING, f"Database sudah penuh")
            except:
                messages.add_message(request, messages.WARNING, f"Ada gangguan, mohon mencoba lain kali")

    else:
        response['lokasi'] = []
        response['lokasi2'] = []
        with connection.cursor() as cursor:
            # cursor.execute('''
            # SELECT DISTINCT *

trigger5/templates/trigger5/batch.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Batch Pengiriman</h1>
    <p class="lead">Melihat Batch</p>
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
</div>
    
<section>
    <h3 class="display-4" style="font-size: 30px;">Batch Pengiriman</h3>
    <td><a href="{% url 'trigger5:batch_lokasi' %}">Buat Badge</a></td>
    <br>
    <td><a href="{% url 'trigger5:detail_batch' %}">Detail Badge</a></td>
    <br>
</section>
  
{% endblock %}

trigger5/templates/trigger5/batch_lokasi.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>BATCH (LOKASI)</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM TAMBAH BATCH (LOKASI)</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger5:batch_lokasi' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Batch Code</div>
        <select id="batch_code" name="batch_code" required>
            <option value="">Choose a code</option>
            {% for batch_code in kodex %}
                <option value="{{batch_code}}">{{batch_code}}</option>
            {% endfor %}
        </select>  

        <div class="pb-1">ID Lokasi Asal</div>
        <select id="asal" name="asal" required>
            <option value="">Choose a code</option>
            {% for asal in code %}
                <option value="{{asal}}">{{asal}}</option>
            {% endfor %}
        </select>  

        <div class="pb-1">ID Lokasi Tujuan</div>
        <select id="tujuan" name="tujuan" required>
            <option value="">Choose a code</option>
            {% for tujuan in code %}
                <option value="{{tujuan}}">{{tujuan}}</option>
            {% endfor %}
        </select>  

        <div class="pb-1">No Kendaraan</div>
        <select id="cars" name="cars" required>
            <option value="">Choose a code</option>
            {% for cars in vehicle %}
                <option value="{{cars}}">{{cars}}</option>
            {% endfor %}
        </select>  

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Register</button>
            <a href='{% url "trigger5:batch" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger5/templates/trigger5/create_faskes.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>FASILITAS KESEHATAN</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM CREATE FASKES</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger5:create_faskes' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        
        <div class="pb-1">Kode Faskes</div>
        <div class="form-group">
          <input type="text" name="codex" value="{{request.POST.codex}}" class="form-width form-control" placeholder="Kode Faskes" required>
        </div>
        
        <div class="pb-1">Id Lokasi</div>
        <select id="id_loc" name="id_loc" required>
            <option value="">Choose an id</option>
            {% for id_loc in id_lokasi %}
                <option value="{{id_loc}}">{{id_loc}}</option>
            {% endfor %}
        </select> 
        
        <div class="pb-1">Petugas Faskes</div>
        <select id="petugas" name="petugas" required>
            <option value="">Choose any petugas</option>
            {% for petugas in petugas_faskes %}
                <option value="{{petugas}}">{{petugas}}</option>
            {% endfor %}
        </select>  
        
        <div class="pb-1">Kode Tipe Faskes</div>
        <select id="kode" name="kode" required>
            <option value="">Choose a code</option>
            {% for kode in kode_tipe_faskes %}
                <option value="{{kode}}">{{kode}}</option>
            {% endfor %}
        </select>  
        
        
        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Register</button>
            <a href='{% url "trigger5:faskes" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger5/templates/trigger5/delete_faskes.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>FASILITAS KESEHATAN</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM DELETE FASKES</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger5:delete_faskes' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Kode</div>
        <div class="form-group">
          <input type="text" name="kode_faskes_nasional" value="{{request.POST.kode_faskes_nasional}}" class="form-width form-control" placeholder="Kode" required>
        </div>
    

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Hapus</button>
            <a href='{% url "trigger5:faskes" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger5/templates/trigger5/delete_warehouse.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>WAREHOUSE SATGAS</title>
{% endblock meta %}
{% block content %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">FORM DELETE WAREHOUSE SATGAS</h3>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} fade show" role="alert">
          {{message}}
        </div>
      {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'trigger5:delete_warehouse' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Kode Lokasi</div>
        <div class="form-group">
          <input type="text" name="id_lokasi" value="{{request.POST.id_lokasi}}" class="form-width form-control" placeholder="id_lokasi" required>
        </div>
    

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Hapus</button>
            <a href='{% url "trigger5:warehouse" %}'>
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

trigger5/templates/trigger5/faskes.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Fasilitas Kesehatan</h1>
    <p class="lead">Melihat fasilitas kesehatan</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
    
    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
        <a href="{% url 'trigger5:create_faskes' %}"><u>Tambahkan fasilitas kesehetan</u></a>
        <br>
    {% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar fasilitas kesehatan</h3>
      <br>
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>Kode Faskes</th>
                    <th>Lokasi</th>
                    <th>Petugas Faskes</th>
                    <th>Tipe Faskes</th>
                    <!-- update/delete -->
                    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
                        <th>Action</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    <!-- keluarin faskes -->
                    {% for kode, lokasi , petugas, tipe in faskes %}
                    <tr class="table-light">
                        <td>{{ kode }}</td>
                        <td>{{ lokasi }}</td>
                        <td>{{ petugas }}</td>
                        <td>{{ tipe }}</td>
                        {% if request.session.pengguna and request.session.role == "admin_satgas"%}
                        <td>
                            <a href="{% url 'trigger5:update_faskes' %}"><u>Update</u></a>
                            <a href="{% url 'trigger5:delete_faskes' %}"><u>Delete</u></a>
                        </td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
{% endblock %}

trigger5/templates/trigger5/index.html
{% extends "home/base.html" %}
{% load static %}
{% block meta %}
<title>FASILITAS DAN LOKASI</title>
{% endblock meta %}
{% block content %}
<div class="jumbotron bg-white text-dark rounded-0 m-0">
    <div class="container">
        <ul class="navbar-nav" style="margin: auto;">
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">
                    <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas"%}
                            <a class="book-link text-light" href="{% url 'trigger5:faskes' %}">
                                Faskes
                            </a>
                        {% elif request.session.pengguna and role == "supplier"%}
                            <a class="book-link text-light" href="{% url 'trigger5:faskes' %}">
                                Faskes
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger5:index' %}">
                                Faskes
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Faskes</h5>
                                <p class="card-text text-justify">CRUD untuk pengguna admin_satgas serta r untuk pengguna supplier</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">

                     <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas"%}
                            <a class="book-link text-light" href="{% url 'trigger5:warehouse' %}">
                                Warehouse Satgas
                            </a>
                        {% elif request.session.pengguna and role == "petugas_faskes"%}
                            <a class="book-link text-light" href="{% url 'trigger5:warehouse' %}">
                                Warehouse Satgas
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger5:index' %}">
                                Warehouse Satgas
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Warehouse Satgas</h5>
                                <p class="card-text text-justify">CRD untuk pengguna admin_satgas serta r untuk pengguna supplier</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <div class="card w-75 border-dark m-3">
                   <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                        {% if request.session.pengguna and role == "admin_satgas"%}
                            <a class="book-link text-light" href="{% url 'trigger5:batch' %}">
                                Batch Pengiriman (Lokasi)
                            </a>
                        {% else %}
                            <a class="book-link text-light" href="{% url 'trigger5:index' %}">
                                Batch Pengiriman (Lokasi)
                            </a>
                        {% endif %}
                    </h3>
                    <div class="card-body bg-main2" style="background-color: rgba(0, 0, 0, 0);">
                        <div class="row">
                            <div class="col-lg-9 col-12 book-info">
                                <h5 class="card-title">Pengaturan Pengiriman (Lokasi)</h5>
                                <p class="card-text text-justify">Create untuk pengguna admin_satgas</p>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

trigger5/templates/trigger5/warehouse.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<div class="jumbotron rounded-0 bg-4">
    <h1 class="display-4">Warehouse Satgas</h1>
    <p class="lead">Melihat Warehouse Satgas</p>
    <hr class="my-4">
    {% if request.session.pengguna %}
      <p class="lead">Selamat datang {{request.session.pengguna}}</p>
      <br>
    {% else %}
      <p class="lead">Selamat datang bung (kami tidak kenal kau)</p>
      <br>
    {% endif %}
    <br>
    
    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
        <a href="{% url 'trigger5:create_warehouse' %}"><u>Tambahkan fasilitas kesehetan</u></a>
        <br>
    {% endif %}
    
    <section>
      <h3 class="display-4" style="font-size: 30px;">Daftar fasilitas kesehatan</h3>
      <br>
      
      <div class="Daftar-Item-Table">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>No.</th>
                    <th>Provinsi</th>
                    <th>Lokasi</th>
                    <!-- update/delete -->
                    {% if request.session.pengguna and request.session.role == "admin_satgas"%}
                        <th>Action</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% block table %}
                  {% endblock %}
                    <!-- keluarin faskes -->
                    {% for provinsi , lokation in lokasi %}
                    <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ provinsi }}</td>
                        <td>{{ lokation }}</td>
                        {% if request.session.pengguna and request.session.role == "admin_satgas"%}
                        <td>
                            <a href="{% url 'trigger5:update_warehouse' %}"><u>Update</u></a>
                            <a href="{% url 'trigger5:delete_warehouse' %}"><u>Delete</u></a>
                        </td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  </tbody>
            </table>
          </div> 
  </div>
</section>
  
{% endblock %}

{% block script %}
<script>
  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#daftar-item-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1 || $(this).attr("id") == "table-header")
      });
    });
  });
  </script>
  <script>
      var subjectObject = {
    "PHP": ["Variables", "Strings", "Arrays"],
    "SQL": ["SELECT", "UPDATE", "DELETE"]
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");
  var chapterSel = document.getElementById("chapter");
  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {
    //empty Chapters- and Topics- dropdowns
    chapterSel.length = 1;
    topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
  topicSel.onchange = function() {
    //empty Chapters dropdown
    chapterSel.length = 1;
    //display correct values
    var z = subjectObject[subjectSel.value][this.value];
    for (var i = 0; i < z.length; i++) {
      chapterSel.options[chapterSel.options.length] = new Option(z[i], z[i]);
    }
  }
}
  </script>
{% endblock %}